import {
  BoardCreatedPayload as ContractsBoardCreatedPayloadSchema,
  BoardDeletedPayload as ContractsBoardDeletedPayloadSchema,
  BoardUpdatedPayload as ContractsBoardUpdatedPayloadSchema,
  CardArchivedPayload as ContractsCardArchivedPayloadSchema,
  CardCancelRequestedPayload as ContractsCardCancelRequestedPayloadSchema,
  CardCleanupProgressedPayload as ContractsCardCleanupProgressedPayloadSchema,
  CardCompletedPayload as ContractsCardCompletedPayloadSchema,
  CardCreatedPayload as ContractsCardCreatedPayloadSchema,
  CardDeletedPayload as ContractsCardDeletedPayloadSchema,
  CardDeleteRequestedPayload as ContractsCardDeleteRequestedPayloadSchema,
  CardOperationFailedPayload as ContractsCardOperationFailedPayloadSchema,
  CardReleasedPayload as ContractsCardReleasedPayloadSchema,
  CardReleaseRequestedPayload as ContractsCardReleaseRequestedPayloadSchema,
  CardResetPayload as ContractsCardResetPayloadSchema,
  CardResetRequestedPayload as ContractsCardResetRequestedPayloadSchema,
  CardRetryRequestedPayload as ContractsCardRetryRequestedPayloadSchema,
  CardSettledPayload as ContractsCardSettledPayloadSchema,
  CardStatusSetPayload as ContractsCardStatusSetPayloadSchema,
  CardStepAdvanceRequestedPayload as ContractsCardStepAdvanceRequestedPayloadSchema,
  CardStepEnteredPayload as ContractsCardStepEnteredPayloadSchema,
  CardTitleUpdatedPayload as ContractsCardTitleUpdatedPayloadSchema,
  CardUnsettledPayload as ContractsCardUnsettledPayloadSchema,
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const BoardCreatedPayload = ContractsBoardCreatedPayloadSchema;
export const BoardUpdatedPayload = ContractsBoardUpdatedPayloadSchema;
export const BoardDeletedPayload = ContractsBoardDeletedPayloadSchema;

export const CardCreatedPayload = ContractsCardCreatedPayloadSchema;
export const CardTitleUpdatedPayload = ContractsCardTitleUpdatedPayloadSchema;
export const CardReleaseRequestedPayload = ContractsCardReleaseRequestedPayloadSchema;
export const CardReleasedPayload = ContractsCardReleasedPayloadSchema;
export const CardStepEnteredPayload = ContractsCardStepEnteredPayloadSchema;
export const CardStepAdvanceRequestedPayload = ContractsCardStepAdvanceRequestedPayloadSchema;
export const CardStatusSetPayload = ContractsCardStatusSetPayloadSchema;
export const CardCompletedPayload = ContractsCardCompletedPayloadSchema;
export const CardRetryRequestedPayload = ContractsCardRetryRequestedPayloadSchema;
export const CardCancelRequestedPayload = ContractsCardCancelRequestedPayloadSchema;
export const CardResetRequestedPayload = ContractsCardResetRequestedPayloadSchema;
export const CardResetPayload = ContractsCardResetPayloadSchema;
export const CardOperationFailedPayload = ContractsCardOperationFailedPayloadSchema;
export const CardCleanupProgressedPayload = ContractsCardCleanupProgressedPayloadSchema;
export const CardSettledPayload = ContractsCardSettledPayloadSchema;
export const CardUnsettledPayload = ContractsCardUnsettledPayloadSchema;
export const CardArchivedPayload = ContractsCardArchivedPayloadSchema;
export const CardDeleteRequestedPayload = ContractsCardDeleteRequestedPayloadSchema;
export const CardDeletedPayload = ContractsCardDeletedPayloadSchema;
